//go:build ignore

// Command generate creates importable wrapper packages from upstream zoekt
// cmd/ directories. For each upstream command it copies all non-test .go files
// into _upstream/<pkgname>/ (underscore prefix so Go tools ignore the
// physical directory), rewriting "package main" to the package name and
// "func main()" to "func Main()".
//
// It also produces a Go build overlay JSON (overlay.json at the repo root)
// that maps these files into zoekt/unified/<pkgname>/ inside the zoekt
// module. This lets them import zoekt's internal packages, which are
// otherwise inaccessible from outside the zoekt module boundary.
//
// Usage:
//
//	go run ./internal/upstream/generate.go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	rePackageMain = regexp.MustCompile(`(?m)^package main$`)
	reFuncMain    = regexp.MustCompile(`(?m)^func main\(\)`)
)

func main() {
	root, err := filepath.Abs(".")
	if err != nil {
		log.Fatal(err)
	}

	upstreamCmdDir := filepath.Join(root, "zoekt", "cmd")
	outputBase := filepath.Join(root, "_upstream")

	entries, err := os.ReadDir(upstreamCmdDir)
	if err != nil {
		log.Fatalf("reading %s: %v", upstreamCmdDir, err)
	}

	// overlay maps virtual (in-zoekt-module) paths to real (on-disk) paths.
	overlay := map[string]string{}

	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}

		cmdName := entry.Name()

		// Derive Go package name: replace hyphens with underscores.
		pkgName := strings.ReplaceAll(cmdName, "-", "_")

		srcDir := filepath.Join(upstreamCmdDir, cmdName)
		dstDir := filepath.Join(outputBase, pkgName)

		goFiles, err := filepath.Glob(filepath.Join(srcDir, "*.go"))
		if err != nil {
			log.Fatalf("glob %s: %v", srcDir, err)
		}

		// Filter out test files.
		var srcFiles []string
		for _, f := range goFiles {
			base := filepath.Base(f)
			if strings.HasSuffix(base, "_test.go") {
				continue
			}
			srcFiles = append(srcFiles, f)
		}

		if len(srcFiles) == 0 {
			continue
		}

		if err := os.MkdirAll(dstDir, 0o755); err != nil {
			log.Fatalf("MkdirAll %s: %v", dstDir, err)
		}

		// Clean old generated files.
		oldFiles, _ := filepath.Glob(filepath.Join(dstDir, "*.go"))
		for _, old := range oldFiles {
			os.Remove(old)
		}

		// Copy any embedded non-Go files (e.g., .json for go:embed).
		for _, ext := range []string{"*.json"} {
			embedFiles, _ := filepath.Glob(filepath.Join(srcDir, ext))
			for _, ef := range embedFiles {
				data, err := os.ReadFile(ef)
				if err != nil {
					log.Fatalf("read %s: %v", ef, err)
				}
				dstEmbed := filepath.Join(dstDir, filepath.Base(ef))
				if err := os.WriteFile(dstEmbed, data, 0o644); err != nil {
					log.Fatalf("write %s: %v", dstEmbed, err)
				}
				virtualPath := filepath.Join(root, "zoekt", "unified", pkgName, filepath.Base(ef))
				overlay[virtualPath] = dstEmbed
			}
		}

		for _, srcFile := range srcFiles {
			data, err := os.ReadFile(srcFile)
			if err != nil {
				log.Fatalf("read %s: %v", srcFile, err)
			}

			content := string(data)

			// Rewrite package declaration.
			content = rePackageMain.ReplaceAllString(content, "package "+pkgName)

			// Rewrite func main() to func Main().
			content = reFuncMain.ReplaceAllString(content, "func Main()")

			// Add generation header.
			header := fmt.Sprintf("// Code generated by internal/upstream/generate.go from zoekt/cmd/%s/%s; DO NOT EDIT.\n\n",
				cmdName, filepath.Base(srcFile))
			content = header + content

			dstFile := filepath.Join(dstDir, filepath.Base(srcFile))
			if err := os.WriteFile(dstFile, []byte(content), 0o644); err != nil {
				log.Fatalf("write %s: %v", dstFile, err)
			}

			// Register in overlay: virtual path inside zoekt module -> real file.
			virtualPath := filepath.Join(root, "zoekt", "unified", pkgName, filepath.Base(srcFile))
			overlay[virtualPath] = dstFile
		}

		fmt.Printf("generated %s (%d files)\n", pkgName, len(srcFiles))
	}

	// Write overlay.json.
	overlayJSON := struct {
		Replace map[string]string `json:"Replace"`
	}{
		Replace: overlay,
	}

	data, err := json.MarshalIndent(overlayJSON, "", "  ")
	if err != nil {
		log.Fatalf("marshal overlay: %v", err)
	}

	overlayPath := filepath.Join(root, "overlay.json")
	if err := os.WriteFile(overlayPath, data, 0o644); err != nil {
		log.Fatalf("write %s: %v", overlayPath, err)
	}

	fmt.Printf("\nwrote %s with %d file mappings\n", overlayPath, len(overlay))
}
